import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import ExcelJS from 'exceljs';
import { format, getISOWeek, parse } from 'date-fns';
import localforage from 'localforage';
import { DragDropContext, Draggable, Droppable, DropResult } from '@hello-pangea/dnd';
import { Copy, Download, Eraser, FileUp, Gear, HelpCircle, RotateCcw, RotateCw, Save, Trash2, Upload, X, AlertTriangle } from 'lucide-react';
import './index.css';

type Field = typeof headers[number];
type Row = Record<Field, string> & { id: string; validFromAutoFilled: boolean; validUntilAutoFilled: boolean };
type ColumnSetting = { key: Field; visible: boolean };
type Preset = { name: string; rows: Row[]; savedAt: string };

const headers = ['title','publishedFrom','publishedUntil','validFrom','validUntil','radius','deliveryChannels','userPlatforms','primaryColor','secondaryColor','publisherId','publisherName','revisionId','storeGroupIds','storeGroups','zipGroupIds','zipGroup','source','group','directLinkOutsEnabled','nearestStoreEnabled','storeDetailsEnabled','ticker','headerImage','headerVideo','headerLinkout','headerLinkoutLabel','fulfillmentCampaign','sector'] as const;
const keyFields = new Set<Field>(['title','publishedFrom','publishedUntil','validFrom','validUntil','radius','deliveryChannels','userPlatforms','publisherId','storeGroupIds','publisherName','source','group','fulfillmentCampaign']);
const dateFields = new Set<Field>(['publishedFrom','publishedUntil','validFrom','validUntil']);
const boolFields = new Set<Field>(['directLinkOutsEnabled','nearestStoreEnabled','storeDetailsEnabled','ticker']);
const deliveryOptions = ['mp','kd'];
const platformOptions = ['mobile.native','mobile.web','desktop.web'];
const fmt = 'dd.MM.yyyy HH:mm';
const storage = localforage.createInstance({ name: 'spotlight-publication-profile-helper' });
const defaultColumns: ColumnSetting[] = headers.map((key) => ({ key, visible: true }));

function nowAt(hour: number) { const d = new Date(); d.setHours(hour, 0, 0, 0); return format(d, fmt); }
function newRow(): Row { return { id: crypto.randomUUID(), title:'', publishedFrom:nowAt(0), publishedUntil:nowAt(23), validFrom:'', validUntil:'', radius:'25', deliveryChannels:'mp;kd', userPlatforms:'mobile.native;mobile.web;desktop.web', primaryColor:'', secondaryColor:'', publisherId:'', publisherName:'', revisionId:'', storeGroupIds:'', storeGroups:'', zipGroupIds:'', zipGroup:'', source:'', group:'', directLinkOutsEnabled:'TRUE', nearestStoreEnabled:'TRUE', storeDetailsEnabled:'TRUE', ticker:'TRUE', headerImage:'', headerVideo:'', headerLinkout:'', headerLinkoutLabel:'', fulfillmentCampaign:'', sector:'', validFromAutoFilled:false, validUntilAutoFilled:false }; }
function clearRow(row: Row): Row { return { ...newRow(), id: row.id }; }
function inputDate(v: string) { const d = parse(v, fmt, new Date()); return Number.isNaN(d.getTime()) ? '' : format(d, "yyyy-MM-dd'T'HH:mm"); }
function displayDate(v: string) { return v ? format(new Date(v), fmt) : ''; }
function isEmptyRequired(row: Row, field: Field) { return keyFields.has(field) && !String(row[field] ?? '').trim() || (row.headerImage.trim() !== '' && (field === 'headerLinkout' || field === 'headerLinkoutLabel') && !row[field].trim()); }
function sanitize(name: string) { return name.replace(/[\\/:*?"<>|]/g, '_').replace(/_+/g, '_').trim(); }

function App() {
  const [rows, setRows] = useState<Row[]>([]); const rowsRef = useRef(rows); rowsRef.current = rows;
  const [past, setPast] = useState<Row[][]>([]); const [future, setFuture] = useState<Row[][]>([]);
  const [columns, setColumns] = useState<ColumnSetting[]>(defaultColumns); const [presets, setPresets] = useState<Preset[]>([]);
  const [toast, setToast] = useState(''); const [settingsOpen, setSettingsOpen] = useState(false); const [bulkOpen, setBulkOpen] = useState(false); const [presetName, setPresetName] = useState('');
  const [revisionImport, setRevisionImport] = useState<Row[] | null>(null); const [bulkDates, setBulkDates] = useState({ publishedFrom: nowAt(0), publishedUntil: nowAt(23) });
  const fileRef = useRef<HTMLInputElement>(null); const importPresetRef = useRef<HTMLInputElement>(null);
  const visibleColumns = useMemo(() => columns.filter(c => c.visible).map(c => c.key), [columns]);
  const pushRows = useCallback((updater: Row[] | ((r: Row[]) => Row[])) => { setRows(prev => { setPast(p => [...p.slice(-39), prev]); setFuture([]); return typeof updater === 'function' ? updater(prev) : updater; }); }, []);
  useEffect(() => { storage.getItem<ColumnSetting[]>('columns').then(v => v && setColumns(v)); storage.getItem<Preset[]>('presets').then(v => v && setPresets(v)); }, []);
  useEffect(() => { storage.setItem('columns', columns); }, [columns]);
  useEffect(() => { storage.setItem('presets', presets); }, [presets]);
  useEffect(() => { const h = (e: KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'z') { e.preventDefault(); e.shiftKey ? redo() : undo(); } }; addEventListener('keydown', h); return () => removeEventListener('keydown', h); });
  const notify = (m: string) => { setToast(m); setTimeout(() => setToast(''), 2600); };
  const undo = () => setPast(p => p.length ? (setFuture(f => [rowsRef.current, ...f]), setRows(p[p.length-1]), p.slice(0,-1)) : p);
  const redo = () => setFuture(f => f.length ? (setPast(p => [...p, rowsRef.current]), setRows(f[0]), f.slice(1)) : f);
  const updateCell = (id: string, field: Field, value: string) => pushRows(rs => rs.map(r => { if (r.id !== id) return r; const n = { ...r, [field]: value }; if (field === 'publishedFrom' && !r.validFromAutoFilled) { n.validFrom = value; n.validFromAutoFilled = true; } if (field === 'publishedUntil' && !r.validUntilAutoFilled) { n.validUntil = value; n.validUntilAutoFilled = true; } return n; }));
  const parseFiles = async (files: FileList | File[]) => { const imported: Row[] = []; let hasRevision = false; for (const file of Array.from(files)) { const wb = new ExcelJS.Workbook(); await wb.xlsx.load(await file.arrayBuffer()); const ws = wb.worksheets[0]; if (!ws) continue; const head = (ws.getRow(1).values as unknown[]).map(String); ws.eachRow((excelRow, i) => { if (i === 1) return; const r = newRow(); headers.forEach(h => { const idx = head.findIndex(x => x === h); if (idx > 0) r[h] = String(excelRow.getCell(idx).text || excelRow.getCell(idx).value || ''); }); if (r.revisionId.trim()) hasRevision = true; imported.push(r); }); } hasRevision ? setRevisionImport(imported) : (pushRows(r => [...r, ...imported]), notify(`Imported ${imported.length} row(s)`)); };
  const downloadXlsx = async () => { const wb = new ExcelJS.Workbook(); const ws = wb.addWorksheet('Publication Profiles'); ws.addRow([...headers]); rows.forEach(r => ws.addRow(headers.map(h => r[h]))); const buf = await wb.xlsx.writeBuffer(); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([buf], { type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })); const first = rows[0]; let filename = 'PublicationProfile.xlsx'; if (first?.group.trim() && first.validFrom.trim()) { const week = String(getISOWeek(parse(first.validFrom, fmt, new Date()))).padStart(2,'0'); filename = `${sanitize(`PublicationProfile_${first.group}_KW${week}`)}.xlsx`; } else if (first) { const ids = [first.title, first.publisherName, first.fulfillmentCampaign].filter(Boolean).map(sanitize); if (ids.length) filename = `${sanitize(`PublicationProfile_${ids.join('_')}`)}.xlsx`; } a.download = filename; a.click(); URL.revokeObjectURL(a.href); notify('Downloaded Excel file'); };
  const savePreset = () => { if (!presetName.trim()) return; setPresets(p => [...p.filter(x => x.name !== presetName.trim()), { name:presetName.trim(), rows, savedAt:new Date().toISOString() }]); setPresetName(''); notify('Preset saved'); };
  const exportPresets = () => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(presets,null,2)], {type:'application/json'})); a.download='spotlight-presets.json'; a.click(); notify('Presets exported'); };
  const importPresets = async (f?: File) => { if (!f) return; const data = JSON.parse(await f.text()) as Preset[]; setPresets(data); notify('Presets imported'); };
  return <div className="min-h-screen"><header className="bg-slate-900 text-white px-6 py-5"><h1 className="text-2xl font-bold">Spotlight Publication Profile Helper</h1></header><main className="p-5 space-y-4">
    {toast && <div className="fixed right-4 top-4 z-50 rounded bg-emerald-600 px-4 py-2 text-white shadow">{toast}</div>}
    <section onDrop={e => { e.preventDefault(); parseFiles(e.dataTransfer.files); }} onDragOver={e=>e.preventDefault()} className="rounded-xl border-2 border-dashed border-blue-300 bg-white p-6 text-center"><FileUp className="mx-auto mb-2 text-blue-700"/><p className="font-semibold">Drop .xlsx files here or browse</p><input ref={fileRef} hidden multiple type="file" accept=".xlsx" onChange={e=>e.target.files && parseFiles(e.target.files)}/><button className="btn mt-3" onClick={()=>fileRef.current?.click()}><Upload size={16}/>Browse files</button></section>
    <section className="flex flex-wrap items-center gap-2 rounded-xl bg-white p-3 shadow"><button className="btn" onClick={()=>setBulkOpen(true)}>Set dates for all rows</button><button className="btn btn-danger" onClick={()=>confirm('Remove all rows?') && pushRows([])}><Trash2 size={16}/>Remove All</button><button className="btn" disabled={!past.length} onClick={undo}><RotateCcw size={16}/>Undo</button><button className="btn" disabled={!future.length} onClick={redo}><RotateCw size={16}/>Redo</button><button className="btn" onClick={()=>setSettingsOpen(true)}><Gear size={16}/>Columns</button><span className="grow"/><input className="cell-input max-w-48" placeholder="Preset name" value={presetName} onChange={e=>setPresetName(e.target.value)}/><button className="btn" onClick={savePreset}><Save size={16}/>Save Preset</button><select className="cell-input max-w-56" onChange={e=>{ const p=presets.find(x=>x.name===e.target.value); if(p && confirm('Load preset and replace current rows?')) pushRows(p.rows); }}><option>Load preset...</option>{presets.map(p=><option key={p.name}>{p.name}</option>)}</select><button className="btn" onClick={()=>{ const n=prompt('Preset to delete?'); if(n&&confirm('Delete preset?')) setPresets(p=>p.filter(x=>x.name!==n));}}>Delete</button><button className="btn" onClick={exportPresets}>Export</button><input ref={importPresetRef} hidden type="file" accept=".json" onChange={e=>importPresets(e.target.files?.[0])}/><button className="btn" onClick={()=>importPresetRef.current?.click()}>Import</button><span className="group relative text-sm text-slate-500">Presets are stored locally in your browser. <HelpCircle className="inline" size={15}/><span className="invisible absolute right-0 top-6 w-80 rounded bg-slate-800 p-2 text-white group-hover:visible">Data is stored in your browser's IndexedDB. To move presets to another device, use the Export/Import feature.</span></span></section>
    <section className="overflow-auto rounded-xl bg-white shadow max-h-[62vh]"><table className="min-w-max border-separate border-spacing-0 text-sm"><thead><tr><th className="sticky left-0 top-0 z-30 bg-slate-100 p-2 shadow">Actions</th>{visibleColumns.map(h=><th key={h} className="sticky top-0 z-20 border-b bg-slate-100 p-2 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="align-top"><td className="sticky left-0 z-10 bg-white p-2 shadow"><div className="flex gap-1"><button title="Remove" onClick={()=>pushRows(rs=>rs.filter(x=>x.id!==r.id))}><Trash2 size={16}/></button><button title="Duplicate" onClick={()=>pushRows(rs=>[...rs,{...r,id:crypto.randomUUID()}])}><Copy size={16}/></button><button title="Clear" onClick={()=>pushRows(rs=>rs.map(x=>x.id===r.id?clearRow(x):x))}><Eraser size={16}/></button></div></td>{visibleColumns.map(f=><td key={f} className="border-b p-2 min-w-52">{renderCell(r,f,updateCell)}</td>)}</tr>)}</tbody></table>{!rows.length && <p className="p-8 text-center text-slate-500">No rows yet. Add a row or upload Excel files.</p>}</section><button className="btn" onClick={()=>pushRows(r=>[...r,newRow()])}>Add Row</button>
    <footer className="sticky bottom-0 flex items-center gap-3 rounded-xl bg-white p-4 shadow"><span className="group relative text-sm text-slate-500">All data is stored locally in your browser. <HelpCircle className="inline" size={15}/><span className="invisible absolute bottom-7 left-0 w-96 rounded bg-slate-800 p-2 text-white group-hover:visible">Your presets and settings are stored in your browser's IndexedDB storage. Use the Export feature to transfer data to another device.</span></span><span className="grow"/><button className="btn btn-primary" onClick={downloadXlsx}><Download size={18}/>Download .xlsx</button></footer>
  </main>{settingsOpen&&<Settings columns={columns} setColumns={setColumns} close={()=>setSettingsOpen(false)}/>} {bulkOpen&&<Modal title="Set dates for all rows" close={()=>setBulkOpen(false)}><DateInput value={bulkDates.publishedFrom} onChange={v=>setBulkDates({...bulkDates,publishedFrom:v})}/><DateInput value={bulkDates.publishedUntil} onChange={v=>setBulkDates({...bulkDates,publishedUntil:v})}/><button className="btn btn-primary mt-4" onClick={()=>{pushRows(rs=>rs.map(r=>({...r,publishedFrom:bulkDates.publishedFrom,publishedUntil:bulkDates.publishedUntil,validFrom:r.validFromAutoFilled?r.validFrom:bulkDates.publishedFrom,validUntil:r.validUntilAutoFilled?r.validUntil:bulkDates.publishedUntil,validFromAutoFilled:true,validUntilAutoFilled:true})));setBulkOpen(false);}}>Apply</button></Modal>} {revisionImport&&<Modal title="Revision IDs found" close={()=>setRevisionImport(null)}><p>The uploaded file(s) contain revisionId values. Would you like to keep or delete them?</p><button className="btn" onClick={()=>{pushRows(r=>[...r,...revisionImport]);setRevisionImport(null);}}>Keep</button><button className="btn btn-primary ml-2" onClick={()=>{pushRows(r=>[...r,...revisionImport.map(x=>({...x,revisionId:''}))]);setRevisionImport(null);}}>Delete</button></Modal>}</div>;
}
function renderCell(row: Row, f: Field, update: (id:string, f:Field, v:string)=>void) { const cls = `cell-input ${isEmptyRequired(row,f)?'required-empty':''}`; if (dateFields.has(f)) return <DateInput className={isEmptyRequired(row,f)?'required-empty':''} value={row[f]} onChange={v=>update(row.id,f,v)}/>; if (f==='radius') return <><input className={cls} type="number" min="1" max="80" step="1" value={row[f]} onChange={e=>update(row.id,f,e.target.value.replace(/\D/g,''))}/><input type="range" min="1" max="80" value={row[f]||25} onChange={e=>update(row.id,f,e.target.value)} className="w-full"/>{(!Number.isInteger(+row[f])||+row[f]<1||+row[f]>80)&&<p className="text-xs text-red-600">Use an integer from 1 to 80.</p>}</>; if (f==='deliveryChannels'||f==='userPlatforms') { const opts=f==='deliveryChannels'?deliveryOptions:platformOptions; const vals=row[f].split(';').filter(Boolean); return <div className={cls}>{opts.map(o=><label key={o} className="mr-3 whitespace-nowrap"><input type="checkbox" checked={vals.includes(o)} onChange={e=>update(row.id,f,e.target.checked?[...vals,o].join(';'):vals.filter(v=>v!==o).join(';'))}/> {o}</label>)}</div>; } if (boolFields.has(f)) return <label className="inline-flex items-center gap-2"><input type="checkbox" checked={row[f]==='TRUE'} onChange={e=>update(row.id,f,e.target.checked?'TRUE':'FALSE')}/> {row[f]}</label>; if (f==='publisherId') return <input className={cls} value={row[f]} onChange={e=>update(row.id,f,e.target.value.replace(/\D/g,''))}/>; return <div className="relative"><input className={cls} value={row[f]} onChange={e=>update(row.id,f,e.target.value)}/>{f==='source'&&row.source&&!row.source.endsWith('.pdf')&&<AlertTriangle title="Check file name — should end in .pdf" className="absolute right-2 top-2 text-yellow-600" size={18}/>}</div>; }
function DateInput({value,onChange,className=''}:{value:string;onChange:(v:string)=>void;className?:string}) { return <input className={`cell-input ${className}`} type="datetime-local" value={inputDate(value)} onChange={e=>onChange(displayDate(e.target.value))}/>; }
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}) { return <div className="modal-backdrop"><div className="modal"><div className="mb-4 flex items-center"><h2 className="text-xl font-bold">{title}</h2><button className="ml-auto" onClick={close}><X/></button></div><div className="space-y-3">{children}</div></div></div>; }
function Settings({columns,setColumns,close}:{columns:ColumnSetting[];setColumns:(c:ColumnSetting[])=>void;close:()=>void}) { const dragEnd = (r: DropResult) => { if (!r.destination) return; const c=[...columns]; const [m]=c.splice(r.source.index,1); c.splice(r.destination.index,0,m); setColumns(c); }; return <Modal title="Column settings" close={close}><DragDropContext onDragEnd={dragEnd}><Droppable droppableId="cols">{p=><div ref={p.innerRef} {...p.droppableProps} className="max-h-96 overflow-auto">{columns.map((c,i)=><Draggable key={c.key} draggableId={c.key} index={i}>{d=><div ref={d.innerRef} {...d.draggableProps} {...d.dragHandleProps} className="mb-2 flex items-center gap-3 rounded border p-2"><span className="cursor-grab">☰</span><label className="grow"><input type="checkbox" checked={c.visible} onChange={e=>setColumns(columns.map(x=>x.key===c.key?{...x,visible:e.target.checked}:x))}/> {c.key}</label></div>}</Draggable>)}{p.placeholder}</div>}</Droppable></DragDropContext></Modal>; }
createRoot(document.getElementById('root')!).render(<App />);
